# Generated by Django 2.2.13 on 2020-11-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='first_interview',
            new_name='first_interviewer',
        ),
        migrations.RenameField(
            model_name='candidate',
            old_name='second_interview',
            new_name='second_interviewer',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='second_remark',
            field=models.CharField(blank=True, max_length=135, verbose_name='专业复试备注'),
        ),
    ]
